name: CDKey
version: '${project.version}'
main: org.poem.cdkey.CDKey
api-version: '1.20'
commands:
  newcdk:
    description: "新建一个cdk"
    usage: /newcdk
    permission: CDKey.newcdk
    permission-message: 你没有权限新建兑换码
  cdk:
    description: "cdk属性设置"
    usage: /cdk <arguments>
    permission: CDKey.cdk
    permission-message: 你没有权限设置兑换码